# fly.toml app configuration file generated for pleasedontshoot on 2024-11-18T13:25:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pleasedontshoot'
primary_region = 'jnb'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  APP_NAME="PDS"
  APP_TIMEZONE="Africa/Johannesburg"
  DISCORD_WEBHOOK="https://discord.com/api/webhooks/1296386814730440736/L-3ZrhWi-IsFiZ4a40PnpDTcalEoV57Ojy0i2Pcsng4wi-5P46dF_M3Be4UtETUnwsps"
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION="sqlite"
  DB_DATABASE="/var/www/html/storage/database/database.sqlite"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
    source = "storage_dir"
    destination = "/var/www/html/storage"

[deploy]
    #release_command = "php artisan migrate --force"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
